[project]
name = "companion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rudraksh Gulati", email = "rudrakshgulati5@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
]

[project.scripts]
companion = "companion:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
