[project]
name = "companion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rudraksh Gulati", email = "rudrakshgulati5@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "google-genai>=2.21.0",
    "numpy>=2.5.2",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
companion = "app.chat:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = ""
